version: "3.8"
services:

    db:
        image: mysql
        container_name: db_dockerTestUnitaire
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_dockerTestUnitaire
        restart: always
        depends_on:
            - db
        ports:
            - "8000:80"
        environment:
            PMA_HOST: db
        networks:
            - dev

    www:
        build: php
        container_name: www_dockerTestUnitaire
        ports:
            - "8743:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www:cached
            - /www/var/cache
        restart: unless-stopped
        networks:
            - dev
networks:
    dev:

volumes:
    db-data: